### PR TITLE
JobTask subclass

### PR DESCRIPTION
**Pull request by rclough**
The goal of this PR is to come down to an acceptable implementation of the JobTask subclass

I pasted over mostof the methods from the Task class and added exceptions to them, so that, at least for the implementation of Jobs-in-Jobs, dagobah will scream if we try to treat a JobTask like a regular task.

The idea is simple, Job task is simply a placeholder with the name of the Job it's referencing, os that when we execute the job, the tasks will be expanded under the hood for actual runtime. Thus this class really only needs the referencing to it's job.

Things to consider: do we want this class to have run logs? Soft/Hard timeouts? I lean towards thingking the logs and timeouts should be kept with the actual job underlying.

Expansion of the JobTask into subtasks will require renaming tasks, as, probably prepending them with the JobTask name, because theoretically you could reference the same job twice in one script.

Is there any other effects of adding this implementation you think should be added into the PR?

### CODE REVIEW

**Comment by rclough** [comment]
I'm back working on this again, I'l probably need to rebase though, since its been a hugely long time, and lots of LOC especially for logging have been added

**Comment by thieman** [comment]
Welcome back!

**Comment by rclough** [comment]
Alright, so pardon my rust as I'm trying to remember things here (looking at the code obviously) just want a sanity check before moving forward.



From what I understand, in mongo, there's really only 1 "table" of importance here and that's dagobah_job, under which just a serialized json of the dagobah job is stored. I think this means that there's really no point in trying to logically separate out the JobTask from the list of all tasks (in the backend), but rather have it deserialized into the appropriate class based on the content of each actual task object from the backend? ie if a task has a non-null value for `job_id` (the job id that the task should expand to) then it will be deserialized as a JobTask, otherwise a regular Task.


For sqlite, I'm not sure why I said to go with a separate table for JobTask: in the backend, I think it makes sense to just have JobTask remain in one table? I feel like having to do a join to get some jobs tasks is a bit complex....all tasks, of all types, should just be in one table, as I think we started out thinking? I also think this would make it really complex to store the edges of the graph, where edges can connect 2 different task ids from separate tables?

You mentioned before,

>There are two separate concepts we are mashing together:

>1. Running a subprocess and storing information about that run
>2. Storing information about various subprocesses that should be replaced for this JobTask during a run

In terms of the subprocess, the objects should be distinct and not necessarily inherent (ie the idea about expandable/runnable is great) but the *storing* of JobTask in the backend should use the same table as task. The transition from 1 task list in the backend, to 2 task types in the front end can be handled by the a non-null job_id

Sorry if any of this sounds either obvious or oblivious. I'm completely removed from any of the ideas I had when I started this so I'm just trying to decode the decisions made up to this point.


sidenote to self for implementation: For Sqlite, we'd need a more complex implementation. In `commit_job` for sqlite, the meat is done in `_update_job_rec`, which leads to `_update_task_rec`, which leads to `update_from_dict` in the sql models for DagobahTask. It seems here that only the columns that exist will be "updated" meaning that as long as we add a job_id column here, the "serialization" process is basically already done. Similar to mongo said above, deserialization is when we distinguish between the task types.

**Comment by thieman** [comment]
> From what I understand, in mongo, there's really only 1 "table" of importance here and that's dagobah_job, under which just a serialized json of the dagobah job is stored. I think this means that there's really no point in trying to logically separate out the JobTask from the list of all tasks (in the backend), but rather have it deserialized into the appropriate class based on the content of each actual task object from the backend? ie if a task has a non-null value for job_id (the job id that the task should expand to) then it will be deserialized as a JobTask, otherwise a regular Task.

Yes. In the `tasks` list on the Job you basically store either the full info for a proper Task or a pointer to another Job, which will be deserialized as a JobTask.

> For sqlite, I'm not sure why I said to go with a separate table for JobTask: in the backend, I think it makes sense to just have JobTask remain in one table? I feel like having to do a join to get some jobs tasks is a bit complex....all tasks, of all types, should just be in one table, as I think we started out thinking? I also think this would make it really complex to store the edges of the graph, where edges can connect 2 different task ids from separate tables?

I think the "JobTask pointers" I just talked about probably need to be represented in their own table in SQL-land. It'll complicate our joins but the alternative is to (potentially) seriously muddy up the existing `DagobahTask` table. Happy to be proven wrong, but we'd need a fleshed out solution to really know.

Also keep in mind for both of these that you should be able to point to the same Job twice as separate JobTasks, e.g. `Execute JobTask A -> Run Task B -> Execute JobTask A`. This is easy in Mongo because you can just mess with the list, but with SQL it seems likely those two runs of `JobTask A` will require separate entries.

**Comment by rclough** [comment]
Yeah, as far as primary keys go, I'm not sure what we currently use for task primary keys (if any) but they should be a unique identifier (possibly just incremented int) because the ability to run a JobTask twice is basically the same as being able to run any other *command* twice (which I'm pretty sure is allowed).

My thought with keeping the JobTask pointers in the same table is that it only requires the addition of one column, which I wouldn't really call muddying up, but it is a slippery slope (ie "what if we just add *one more* column"). That said I'm not sure what else would really be added to tasks in the future. Having job pointers in the task table doesn't seem like that big a deal to me because thats how they are in the front end too, they're all logically "Tasks" just theres 2 types of tasks now.

We can do them separately I just thought it might make more sense to keep tasks together, since they are in the front end, and with mongo already. And I worry about how edges are going to be done when it could be pointing to primary keys across 2 different tables (as I understand)

**Comment by rclough** [comment]
So back on this....if we are in fact going to go with a separate table, what do you think is the best way to store edges? Right now, there's the SQLITE model `DagobahDependency` which has `id`, `job_id`, `from_task_id`, and `to_task_id`. Since we will have 2 tables (`dagobah_task`, and a presumably new `dagobah_jobtask`). We either need to ensure unique IDs across both tables (I'm not aware of an elegant solution for this), or use some sort of signifier in the DagobahDependency object/table that indicates if the FROM and TO are IDs for the `dagobah_task` table or `dagobah_jobtask` table


My first thought RE: signifier is the be clever and just do a 2 bit "binary" signifier:

00 = from task to task
01 = from task to jobtask
10 = from jobtask to task
11: from jobtask to jobtask

but sometimes cleverness isn't clear, so maybe some enumerated value or something?

Thoughts?

**Comment by rclough** [comment]
(half joking pre-amble: can we just drop sql support? :cold_sweat: )

Actually, in `sqlite_models.py`, the `DagobahDependency` "object", which corresponds to the `dagobah_dependency` table, uses foreign keys to denote that `from_task` and `to_task` are to be found in `dagobah_task`. AFAIK it's not possible to declare multiple foreign keys for the same column.

We can, however, remove the foreign key constraint. Then we are stuck with the complexity of handling constraints manually (possibly in a manner similar to what I mentioned in the last post). This is not....elegant, but it is doable. This will remove a lot of the handy code that makes our SQL management library useful though. because then we can't define a `relationship` properly as it is now:

screenshot 2015-05-20 16 20 27

**Comment by rclough** [comment]
Another idea might be to turn the tasks table....into 3 tables, which MAY NOT be backwards compatible (lol, bare with me):

1. `dagobah_task`: literally just a list of "ids" for tasks, maybe a second column that tells you which table to look for this specific task
2. `dagobah_task_command`: table similar to what we currently have, with the ID field a foreign key with `dagobah_task`, and then the rest of the info to execute the task (which is essentially a "command")
3. `dagobah_task_job`: Similar to above, it has a foreign key with `dagobah_task` for the ID. the other column would be a foreign key with the job ID we want to execute

This way we can still take advantage of things like relationships (aka the dagobah_dependency table can just have from_task and to_task foreign key with `dagobah_task`. Deserialization would did into the appropriate table for the task from there.

**Comment by rclough** [comment]
closing cause this is replaced by #155

**Pull request closed without merging**
