### PR TITLE
Try to make dict comparison stop flapping

### PR DESCRIPTION
**Pull request by thieman**
cc @rclough

### CODE REVIEW

**Comment by thieman** [comment]
UUUUUUUGH PYTHON 2.6

**Comment by rclough** [comment]
:+1:

**Comment by rclough** [comment]
by the way, this test still flaps (actually exclusively fails) for me. I thought at first it was cause I was still working off an older branch but I've confirmed I'm using asser_equals as in this PR and its still failing here, passing on travis.

**Comment by thieman** [comment]
uuuuuuuuuugh

**Pull request merged**
