### PR TITLE
Is this feature still in beta?

### PR DESCRIPTION
**Pull request by thieman**
testing travis

### CODE REVIEW

**Comment by rclough** [comment]
Out of curiosity, wtf is this

**Comment by thieman** [comment]
Was testing to see whether Travis had brought this out of beta yet http://docs.travis-ci.com/user/multi-os/

**Comment by rclough** [comment]
OH took me a minute, I thought you were talking in 3rd person haha

**Comment by thieman** [comment]
No worries. I am actually a sentient CI suite, and even I get confused sometimes and think I am a human.

**Pull request closed without merging**
