### PR TITLE
Switched broken pypip.in badges to shields.io

### PR DESCRIPTION
**Pull request by movermeyer**
Hello, this is an auto-generated Pull Request. ([Feedback?](mailto:repobot@movermeyer.com?subject=pypip.in%20Badge%20Bot%20Feedback%3A%20dagobah))

Some time ago, [pypip.in](https://web.archive.org/web/20150318013508/https://pypip.in/) shut down. This broke the badges for a bunch of repositories, including `dagobah`. Thankfully, an equivalent service is run by [shields.io](https://shields.io). This pull request changes the badge to use shields.io instead.

### CODE REVIEW

**Comment by thieman** [comment]
Closing as this seems to be bringing in a ton of unrelated commits, I'm guessing from someone else's fork.

**Comment by movermeyer** [comment]
My apologies.

It appears that for some reason, when the program asked GitHub to fork `thieman/dagobah`, it ended up forking [Littlegump/dagobah](https://github.com/Littlegump/dagobah) instead.

Then my code applied the change to that fork, and tried to merge it into your repo.

I'm still not sure why that happened. I have tried again, and the code worked fine (ie. it's not reproducible) 
I suspect there is some indexing/timing issue on GitHub's side.

I'll have to investigate further before I allow my bot to continue.

Again, my deepest apologies for the inconvenience.

**Comment by movermeyer** [comment]
[**Solved:** My bot processed `Littlegump/dagobah` first, which created `movermeyer/dagobah`. When it came to process `thieman/dagobah` it reused the same fork. I have made changes to my bot so this won't happen again. Sorry for the inconvenience.]

**Comment by thieman** [comment]
Happy to help. If provided with a legit PR for switching to shields I would probably merge it.

**Pull request closed without merging**
